name: Release action

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT }}
          release-type: simple 

      - name: Checkout repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4 
  
      - name: Rename file
        if: ${{ steps.release.outputs.release_created }}
        run: mv ./build/main.pdf ./report.pdf

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./report.pdf 
